services:
  kafka:
    container_name: kafka
    image: quay.io/ccxdev/kafka-no-zk:latest
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=ols-new-archive:1:1
  
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001  # console
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:9001
    command:
      - server
      - /data

  createbuckets:
    image: minio/mc:latest
    depends_on: 
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set minio http://minio:9000 minio minio123 &&
        mc mb minio/external-storage &&
        mc mb minio/internal-storage-io &&
        mc mb minio/internal-storage-ols &&
        tail -f /dev/null
      "

  archive-sync-ols:
    image: quay.io/redhat-services-prod/obsint-processing-tenant/ccx-messaging/ccx-messaging:latest
    container_name: archive-sync-ols
    command:
      - ccx-messaging
      - /archive-sync-ols.yaml
    volumes:
      - ./archive-sync-ols.yaml:/archive-sync-ols.yaml
    environment:
      - KAFKA_URL=kafka:9092
      - NEW_ARCHIVE_TOPIC=ols-new-archive

      - EXTERNAL_S3_URL=http://minio:9000
      - EXTERNAL_S3_ACCESS_KEY=minio
      - EXTERNAL_S3_SECRET_KEY=minio123
      - EXTERNAL_S3_BUCKET=external-storage

      - INTERNAL_S3_URL=http://minio:9000
      - INTERNAL_S3_ACCESS_KEY=minio
      - INTERNAL_S3_SECRET_KEY=minio123
      - INTERNAL_S3_BUCKET=internal-storage-ols
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_started

networks:
  default:
    name: internal-data-pipeline
