plugins:
  packages:
    - ccx_messaging
service:
    extract_timeout:
    extract_tmp_dir:
    format: insights.formats._json.JsonFormat
    target_components: []
    consumer:
      name: ccx_messaging.consumers.decoded_ingress_consumer.DecodedIngressConsumer
      kwargs:
        incoming_topic: ${KAFKA_INCOMING_TOPIC}
        group.id: ${KAFKA_GROUP_ID}
        bootstrap.servers: localhost:9092
        processing_timeout_s: 0
        max.poll.interval.ms: 600000
        heartbeat.interval.ms: 10000
        session.timeout.ms: 20000
    downloader:
      name: ccx_messaging.downloaders.http_downloader.HTTPDownloader
      kwargs:
        allow_unsafe_links: ${ALLOW_UNSAFE_LINKS}
    engine:
          name: ccx_messaging.engines.multiplexor_engine.MultiplexorEngine
          kwargs:
            filters:
              openshift_lightspeed.json: OLS
    publisher:
      name: ccx_messaging.publishers.synced_archive_publisher.SyncedArchivePublisher
      kwargs:
        outgoing_topic: ${KAFKA_OUTGOING_TOPIC}
        bootstrap.servers: localhost:9092
    watchers:
      - name: ccx_messaging.watchers.stats_watcher.StatsWatcher
        kwargs:
          prometheus_port: 8000
      - name: ccx_messaging.watchers.payload_tracker_watcher.PayloadTrackerWatcher
        kwargs:
          bootstrap.servers: localhost:9092
          topic: ${PAYLOAD_TRACKER_TOPIC}
          service_name: archive-sync
    logging:
      version: 1
      disable_existing_loggers: false
      handlers:
        default:
          level: DEBUG
          class: logging.StreamHandler
          stream: ext://sys.stdout
          formatter: default
      formatters:
        default:
          format: '%(asctime)s %(name)s %(levelname)-8s %(message)s'
          datefmt: '%Y-%m-%d %H:%M:%S'
      root:
        level: INFO
        handlers:
          - default
      loggers:
        ccx_messaging:
          level: INFO
        insights_messaging:
          level: WARNING
        insights:
          level: DEBUG
        kafka:
          level: WARNING
